/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as AuthVerifyotpRouteImport } from './routes/auth/verifyotp'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetpasswordRouteImport } from './routes/auth/resetpassword'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotpasswordRouteImport } from './routes/auth/forgotpassword'
import { Route as AuthChangepasswordRouteImport } from './routes/auth/changepassword'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as StudentLessonsLessonIdRouteImport } from './routes/student/lessons/$lessonId'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student/courses/$courseId'
import { Route as AdminCoursesCreateRouteImport } from './routes/admin/courses/create'
import { Route as AdminCoursesCourseIdSectionsRouteImport } from './routes/admin/courses/$courseId/sections'
import { Route as AdminCoursesCourseIdSectionIdLessonsRouteImport } from './routes/admin/courses/$courseId/$sectionId/lessons'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/instructor/dashboard',
  path: '/instructor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyotpRoute = AuthVerifyotpRouteImport.update({
  id: '/verifyotp',
  path: '/verifyotp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetpasswordRoute = AuthResetpasswordRouteImport.update({
  id: '/resetpassword',
  path: '/resetpassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotpasswordRoute = AuthForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthChangepasswordRoute = AuthChangepasswordRouteImport.update({
  id: '/changepassword',
  path: '/changepassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/admin/__layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/admin/students/',
  path: '/admin/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLessonsLessonIdRoute = StudentLessonsLessonIdRouteImport.update({
  id: '/student/lessons/$lessonId',
  path: '/student/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/student/courses/$courseId',
  path: '/student/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesCreateRoute = AdminCoursesCreateRouteImport.update({
  id: '/admin/courses/create',
  path: '/admin/courses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesCourseIdSectionsRoute =
  AdminCoursesCourseIdSectionsRouteImport.update({
    id: '/admin/courses/$courseId/sections',
    path: '/admin/courses/$courseId/sections',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoursesCourseIdSectionIdLessonsRoute =
  AdminCoursesCourseIdSectionIdLessonsRouteImport.update({
    id: '/admin/courses/$courseId/$sectionId/lessons',
    path: '/admin/courses/$courseId/$sectionId/lessons',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/changepassword': typeof AuthChangepasswordRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verifyotp': typeof AuthVerifyotpRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/lessons/$lessonId': typeof StudentLessonsLessonIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/courses/$courseId/sections': typeof AdminCoursesCourseIdSectionsRoute
  '/admin/courses/$courseId/$sectionId/lessons': typeof AdminCoursesCourseIdSectionIdLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/changepassword': typeof AuthChangepasswordRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verifyotp': typeof AuthVerifyotpRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/lessons/$lessonId': typeof StudentLessonsLessonIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/courses/$courseId/sections': typeof AdminCoursesCourseIdSectionsRoute
  '/admin/courses/$courseId/$sectionId/lessons': typeof AdminCoursesCourseIdSectionIdLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/__layout': typeof Admin_layoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/changepassword': typeof AuthChangepasswordRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verifyotp': typeof AuthVerifyotpRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/lessons/$lessonId': typeof StudentLessonsLessonIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/courses/$courseId/sections': typeof AdminCoursesCourseIdSectionsRoute
  '/admin/courses/$courseId/$sectionId/lessons': typeof AdminCoursesCourseIdSectionIdLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/auth/changepassword'
    | '/auth/forgotpassword'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/auth/signup'
    | '/auth/verifyotp'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/student/profile'
    | '/admin/'
    | '/admin/courses/create'
    | '/student/courses/$courseId'
    | '/student/lessons/$lessonId'
    | '/admin/courses/'
    | '/admin/students/'
    | '/admin/courses/$courseId/sections'
    | '/admin/courses/$courseId/$sectionId/lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/auth/changepassword'
    | '/auth/forgotpassword'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/auth/signup'
    | '/auth/verifyotp'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/student/profile'
    | '/admin/courses/create'
    | '/student/courses/$courseId'
    | '/student/lessons/$lessonId'
    | '/admin/courses'
    | '/admin/students'
    | '/admin/courses/$courseId/sections'
    | '/admin/courses/$courseId/$sectionId/lessons'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/login'
    | '/admin/__layout'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/auth/changepassword'
    | '/auth/forgotpassword'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/auth/signup'
    | '/auth/verifyotp'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/student/profile'
    | '/admin/'
    | '/admin/courses/create'
    | '/student/courses/$courseId'
    | '/student/lessons/$lessonId'
    | '/admin/courses/'
    | '/admin/students/'
    | '/admin/courses/$courseId/sections'
    | '/admin/courses/$courseId/$sectionId/lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentProfileRoute: typeof StudentProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCreateRoute: typeof AdminCoursesCreateRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
  StudentLessonsLessonIdRoute: typeof StudentLessonsLessonIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminCoursesCourseIdSectionsRoute: typeof AdminCoursesCourseIdSectionsRoute
  AdminCoursesCourseIdSectionIdLessonsRoute: typeof AdminCoursesCourseIdSectionIdLessonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verifyotp': {
      id: '/auth/verifyotp'
      path: '/verifyotp'
      fullPath: '/auth/verifyotp'
      preLoaderRoute: typeof AuthVerifyotpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgotpassword': {
      id: '/auth/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/auth/forgotpassword'
      preLoaderRoute: typeof AuthForgotpasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/changepassword': {
      id: '/auth/changepassword'
      path: '/changepassword'
      fullPath: '/auth/changepassword'
      preLoaderRoute: typeof AuthChangepasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/lessons/$lessonId': {
      id: '/student/lessons/$lessonId'
      path: '/student/lessons/$lessonId'
      fullPath: '/student/lessons/$lessonId'
      preLoaderRoute: typeof StudentLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/student/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/create': {
      id: '/admin/courses/create'
      path: '/admin/courses/create'
      fullPath: '/admin/courses/create'
      preLoaderRoute: typeof AdminCoursesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$courseId/sections': {
      id: '/admin/courses/$courseId/sections'
      path: '/admin/courses/$courseId/sections'
      fullPath: '/admin/courses/$courseId/sections'
      preLoaderRoute: typeof AdminCoursesCourseIdSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$courseId/$sectionId/lessons': {
      id: '/admin/courses/$courseId/$sectionId/lessons'
      path: '/admin/courses/$courseId/$sectionId/lessons'
      fullPath: '/admin/courses/$courseId/$sectionId/lessons'
      preLoaderRoute: typeof AdminCoursesCourseIdSectionIdLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthChangepasswordRoute: typeof AuthChangepasswordRoute
  AuthForgotpasswordRoute: typeof AuthForgotpasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyotpRoute: typeof AuthVerifyotpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChangepasswordRoute: AuthChangepasswordRoute,
  AuthForgotpasswordRoute: AuthForgotpasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyotpRoute: AuthVerifyotpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  Admin_layoutRoute: Admin_layoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentProfileRoute: StudentProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCreateRoute: AdminCoursesCreateRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
  StudentLessonsLessonIdRoute: StudentLessonsLessonIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminCoursesCourseIdSectionsRoute: AdminCoursesCourseIdSectionsRoute,
  AdminCoursesCourseIdSectionIdLessonsRoute:
    AdminCoursesCourseIdSectionIdLessonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
